--- #this is my task playbook
- hosts: webserevers
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: installing httpd in webservers
            action: yum name=htpd state=installed
            ignore_errors: yes
